import type { Doctor } from "@/types";
import { Brain, Heart, Stethoscope, Bone, Baby, User, Ear, Eye, UserCog } from 'lucide-react';

export const doctorsData: Doctor[] = [
    {
      id: "1",
      name: "डॉ. रमेश कुमार",
      specialization: "हृदय रोग विशेषज्ञ",
      description: "डॉ. रमेश कुमार गोपालगंज में एक प्रमुख हृदय रोग विशेषज्ञ हैं, जो हृदय से संबंधित बीमारियों और निवारक देखभाल में विशेषज्ञता रखते हैं। 15 से अधिक वर्षों के अनुभव के साथ, वह अपने रोगी-केंद्रित दृष्टिकोण और जटिल हृदय स्थितियों के प्रबंधन में अपनी विशेषज्ञता के लिए जाने जाते हैं।",
      fee: 500,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=RK",
      location: "पुरानी चौक, सिनेमा रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "2",
      name: "डॉ. सुनीता शर्मा",
      specialization: "बच्चों का चिकित्सक",
      description: "डॉ. सुनीता शर्मा बच्चों के स्वास्थ्य और कल्याण के लिए समर्पित एक बाल रोग विशेषज्ञ हैं। वह शैशवावस्था से किशोरावरावस्था तक व्यापक देखभाल प्रदान करती हैं, जिसमें विकासात्मक निगरानी, टीकाकरण और सामान्य बचपन की बीमारियों का उपचार शामिल है।",
      fee: 400,
      imageUrl: "https://placehold.co/128x128/EC4899/FFFFFF/png?text=SS",
      location: "अस्पताल रोड, गोपालगंज",
      aiHint: "indian female doctor",
    },
    {
      id: "3",
      name: "डॉ. अनिल सिंह",
      specialization: "त्वचा विशेषज्ञ",
      description: "डॉ. अनिल सिंह एक अनुभवी त्वचा विशेषज्ञ हैं जो त्वचा, बाल और नाखूनों की कई स्थितियों का इलाज करते हैं। उनकी विशेषज्ञता में कॉस्मेटिक त्वचाविज्ञान, मुँहासे का उपचार और सोरायसिस और एक्जिमा जैसी पुरानी त्वचा रोगों का प्रबंधन शामिल है।",
      fee: 600,
      imageUrl: "https://placehold.co/128x128/F59E0B/FFFFFF/png?text=AS",
      location: "बस स्टैंड के पास, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "4",
      name: "डॉ. मीना गुप्ता",
      specialization: "स्त्री रोग विशेषज्ञ",
      description: "डॉ. मीना गुप्ता एक दयालु स्त्री रोग विशेषज्ञ और प्रसूति विशेषज्ञ हैं जो महिलाओं की स्वास्थ्य सेवाओं की पूरी श्रृंखला प्रदान करती हैं। वह रोगी के आराम और देखभाल पर ध्यान देने के साथ प्रसव पूर्व देखभाल, प्रसव और स्त्री रोग संबंधी समस्याओं के प्रबंधन में माहिर हैं।",
      fee: 550,
      imageUrl: "https://placehold.co/128x128/8B5CF6/FFFFFF/png?text=MG",
      location: "थावे रोड, गोपालगंज",
      aiHint: "indian female doctor",
    },
      {
      id: "5",
      name: "डॉ. विक्रम पटेल",
      specialization: "हड्डी रोग विशेषज्ञ",
      description: "डॉ. विक्रम पटेल एक प्रसिद्ध हड्डी रोग विशेषज्ञ हैं, जिन्हें जोड़ों के प्रतिस्थापन, खेल की चोटों और फ्रैक्चर की देखभाल में विशेषज्ञता हासिल है। वह सर्जिकल और गैर-सर्जिकल उपचारों के माध्यम से गतिशीलता बहाल करने और अपने रोगियों के जीवन की गुणवत्ता में सुधार करने के लिए समर्पित हैं।",
      fee: 700,
      imageUrl: "https://placehold.co/128x128/10B981/FFFFFF/png?text=VP",
      location: "जाधवपुर रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "6",
      name: "डॉ. प्रिया देसाई",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. प्रिया देसाई एक विश्वसनीय सामान्य चिकित्सक हैं जो वयस्कों के लिए प्राथमिक देखभाल प्रदान करती हैं। वह विभिन्न प्रकार की बीमारियों का निदान और उपचार करने, पुरानी स्थितियों का प्रबंधन करने और निवारक देखभाल के माध्यम से समग्र स्वास्थ्य और कल्याण को बढ़ावा देने पर ध्यान केंद्रित करती हैं।",
      fee: 300,
      imageUrl: "https://placehold.co/128x128/EF4444/FFFFFF/png?text=PD",
      location: "कचहरी रोड, गोपालगंज",
      aiHint: "indian female doctor",
    },
    {
      id: "7",
      name: "डॉ. शंभू नाथ सिंह",
      specialization: "जनरल सर्जन",
      description: "डॉ. शंभू नाथ सिंह एक कुशल जनरल सर्जन हैं, जो विभिन्न प्रकार की सर्जिकल प्रक्रियाओं में विशेषज्ञता रखते हैं। वह न्यूनतम इनवेसिव सर्जरी और रोगी की त्वरित रिकवरी पर ध्यान केंद्रित करते हैं।",
      fee: 800,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=SNS",
      location: "मौनिया चौक, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "8",
      name: "डॉ. राजेश वर्मा",
      specialization: "तंत्रिका विज्ञानी",
      description: "डॉ. राजेश वर्मा एक अनुभवी न्यूरोलॉजिस्ट हैं जो मस्तिष्क, रीढ़ की हड्डी और तंत्रिकाओं के विकारों का इलाज करते हैं।",
      fee: 900,
      imageUrl: "https://placehold.co/128x128/F59E0B/FFFFFF/png?text=RV",
      location: "अंबेडकर चौक, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "9",
      name: "डॉ. अंजलि मेहता",
      specialization: "ईएनटी विशेषज्ञ",
      description: "डॉ. अंजलि मेहता कान, नाक और गले से संबंधित विकारों के निदान और उपचार में माहिर हैं।",
      fee: 450,
      imageUrl: "https://placehold.co/128x128/EC4899/FFFFFF/png?text=AM",
      location: "पोस्ट ऑफिस चौक, गोपालगंज",
      aiHint: "indian female doctor",
    },
    {
      id: "10",
      name: "डॉ. दीपक चौहान",
      specialization: "नेत्र रोग विशेषज्ञ",
      description: "डॉ. दीपक चौहान एक कुशल नेत्र रोग विशेषज्ञ हैं जो आंखों की बीमारियों का इलाज करते हैं और दृष्टि देखभाल प्रदान करते हैं।",
      fee: 500,
      imageUrl: "https://placehold.co/128x128/10B981/FFFFFF/png?text=DC",
      location: "गोशाला रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "11",
      name: "डॉ. पवन कुमार",
      specialization: "मनोचिकित्सक",
      description: "डॉ. पवन कुमार एक अनुभवी मनोचिकित्सक हैं जो मानसिक स्वास्थ्य संबंधी समस्याओं का इलाज करते हैं। वह तनाव, अवसाद और चिंता जैसे मुद्दों पर विशेषज्ञ परामर्श प्रदान करते हैं।",
      fee: 650,
      imageUrl: "https://placehold.co/128x128/8B5CF6/FFFFFF/png?text=PK",
      location: "चंद्रगोकुल रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "12",
      name: "डॉ. देवता सिंह",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. देवता सिंह एक अनुभवी सामान्य चिकित्सक हैं जो सभी उम्र के रोगियों को व्यापक स्वास्थ्य सेवा प्रदान करते हैं। वह बीमारियों के निदान और उपचार के साथ-साथ निवारक देखभाल पर भी ध्यान केंद्रित करते हैं।",
      fee: 350,
      imageUrl: "https://placehold.co/128x128/EF4444/FFFFFF/png?text=DS",
      location: "मेडिकल हॉल, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "13",
      name: "डॉ. अभिषेक शेखर सिन्हा",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. अभिषेक शेखर सिन्हा एक जाने-माने सामान्य चिकित्सक हैं जो सभी प्रकार की सामान्य बीमारियों के लिए विश्वसनीय देखभाल प्रदान करते हैं। वह रोगी के समग्र स्वास्थ्य पर ध्यान केंद्रित करते हैं।",
      fee: 350,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=ASS",
      location: "टाउन हॉल, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "14",
      name: "डॉ. रामप्रवेश सिंह",
      specialization: "बच्चों का चिकित्सक",
      description: "डॉ. रामप्रवेश सिंह एक समर्पित बाल रोग विशेषज्ञ हैं जो शिशुओं, बच्चों और किशोरों को व्यापक चिकित्सा देखभाल प्रदान करते हैं। वह बाल स्वास्थ्य और कल्याण सुनिश्चित करने के लिए जाने जाते हैं।",
      fee: 400,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=RS",
      location: "सिविल लाइंस, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "15",
      name: "डॉ. शिवेंद्र कुमार तिवारी",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. शिवेंद्र कुमार तिवारी एक अनुभवी सामान्य चिकित्सक हैं जो सभी प्रकार की सामान्य बीमारियों के लिए विश्वसनीय देखभाल प्रदान करते हैं।",
      fee: 350,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=SKT",
      location: "सिविल लाइंस, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "16",
      name: "डॉ. अभिषेक रंजन",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. अभिषेक रंजन एक जाने-माने सामान्य चिकित्सक हैं जो सभी प्रकार की सामान्य बीमारियों के लिए विश्वसनीय देखभाल प्रदान करते हैं।",
      fee: 400,
      imageUrl: "https://placehold.co/128x128/EC4899/FFFFFF/png?text=AR",
      location: "अस्पताल रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "17",
      name: "डॉ. अरविंद कुमार",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. अरविंद कुमार एक विश्वसनीय सामान्य चिकित्सक हैं जो वयस्कों के लिए प्राथमिक देखभाल प्रदान करते हैं।",
      fee: 300,
      imageUrl: "https://placehold.co/128x128/F59E0B/FFFFFF/png?text=AK",
      location: "बस स्टैंड के पास, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "18",
      name: "डॉ. मुकेश कुमार सिंह",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. मुकेश कुमार सिंह सभी उम्र के रोगियों को व्यापक स्वास्थ्य सेवा प्रदान करते हैं।",
      fee: 350,
      imageUrl: "https://placehold.co/128x128/8B5CF6/FFFFFF/png?text=MKS",
      location: "थावे रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "19",
      name: "डॉ. श्याम मोहन सिंह",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. श्याम मोहन सिंह बीमारियों के निदान और उपचार के साथ-साथ निवारक देखभाल पर भी ध्यान केंद्रित करते हैं।",
      fee: 300,
      imageUrl: "https://placehold.co/128x128/10B981/FFFFFF/png?text=SMS",
      location: "जाधवपुर रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "20",
      name: "डॉ. विनीत विनोद कुमार यादव",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. विनीत विनोद कुमार यादव एक अनुभवी सामान्य चिकित्सक हैं जो रोगी के समग्र स्वास्थ्य पर ध्यान केंद्रित करते हैं।",
      fee: 400,
      imageUrl: "https://placehold.co/128x128/EF4444/FFFFFF/png?text=VVKY",
      location: "कचहरी रोड, गोपालगंज",
      aiHint: "indian male doctor",
    },
    {
      id: "21",
      name: "डॉ. सौरभ अग्रवाल",
      specialization: "सामान्य चिकित्सक",
      description: "डॉ. सौरभ अग्रवाल एक अनुभवी सामान्य चिकित्सक हैं जो सभी उम्र के रोगियों को व्यापक स्वास्थ्य सेवा प्रदान करते हैं। वह बीमारियों के निदान और उपचार के साथ-साथ निवारक देखभाल पर भी ध्यान केंद्रित करते हैं।",
      fee: 400,
      imageUrl: "https://placehold.co/128x128/3B82F6/FFFFFF/png?text=SA",
      location: "सिनेमा रोड, गोपालगंज",
      aiHint: "indian male doctor",
    }
  ];

  export const specializationMap = [
    { name: "हृदय रोग विशेषज्ञ", icon: Heart },
    { name: "बच्चों का चिकित्सक", icon: Baby },
    { name: "त्वचा विशेषज्ञ", icon: User },
    { name: "स्त्री रोग विशेषज्ञ", icon: Stethoscope },
    { name: "हड्डी रोग विशेषज्ञ", icon: Bone },
    { name: "सामान्य चिकित्सक", icon: Stethoscope },
    { name: "जनरल सर्जन", icon: Stethoscope },
    { name: "तंत्रिका विज्ञानी", icon: Brain },
    { name: "ईएनटी विशेषज्ञ", icon: Ear },
    { name: "नेत्र रोग विशेषज्ञ", icon: Eye },
    { name: "मनोचिकित्सक", icon: UserCog },
  ];
